//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.DB_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal SellPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
